### ISSUE TITLE
Reimplement this with LLVM

### ISSUE THREAD

**Issue by Naville** [godshield/iPAObfuscator#1]
I've already explained the reasons through separate communication meanings.
This whole thing could be easily archived with full FAT MachO support and whatnot by using Clang/LLVM APIs only.

Try harder as this provides better portability and stability, and could be done in ~200 lines of code. If this is too time-consuming for your people I will craft it by myself someday.

Zhang

**Comment by Naville** [comment]
LLVM has provided a full-fledged Binary Parsing library under [include/llvm/Object](https://github.com/llvm/llvm-project/tree/master/llvm/include/llvm/Object) which should be more than enough to suit your needs for extracting the BC segment.  Unpacking xar should be even more straightforward. The only difficult left is to emulate Clang's driver and construct the libClang instances but in that sense copy and pasting is your friend :)

**Comment by godshield** [comment]
Thanks for your advice. I'll try it

**Comment by fukun521** [comment]
Last login: Tue Dec  3 15:36:56 on ttys000
➜  ~ python

WARNING: Python 2.7 is not recommended. 
This version is included in macOS for compatibility with legacy software. 
Future versions of macOS will not include Python 2.7. 
Instead, it is recommended that you transition to using 'python3' from within Terminal.

Python 2.7.16 (default, Aug 24 2019, 18:37:03) 
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.32.4) (-macos10.15-objc-s on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> cd /Users/qwr-and-dev2/development/iPAObfuscator 
  File "<stdin>", line 1
    cd /Users/qwr-and-dev2/development/iPAObfuscator 
                    ^
SyntaxError: invalid syntax
>>> 
[1]  + 77841 suspended  python
➜  ~ cd /Users/qwr-and-dev2/development/iPAObfuscator 
➜  iPAObfuscator git:(master) ls
README.md          before.png         bundle.py          main.py
__init__.py        bin                cmd.py             plist_analysis.py
after.png          binary_analysis.py fileParse.py       util.py
bctest             buildEnv.py        macho.py
➜  iPAObfuscator git:(master) ls
README.md          before.png         bundle.py          main.py
__init__.py        bin                cmd.py             plist_analysis.py
after.png          binary_analysis.py fileParse.py       util.py
bctest             buildEnv.py        macho.py
➜  iPAObfuscator git:(master) python main.py bctest.ipa --taskId 0011 -o bctest/
[LOG] Extracting IPA File
[LOG] Unzipping
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    main(sys.argv)
  File "main.py", line 36, in main
    outDict = fParse.getRealFile(args.task_id)
  File "/Users/qwr-and-dev2/development/iPAObfuscator/fileParse.py", line 183, in getRealFile
    self.unzip(srcPath, pro_dict['unzip_dir'])
  File "/Users/qwr-and-dev2/development/iPAObfuscator/fileParse.py", line 66, in unzip
    with zipfile.ZipFile(app_path, "r") as zipptr:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 779, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: '/Users/qwr-and-dev2/development/iPAObfuscator/tmp/0011/bctest.ipa'
➜  iPAObfuscator git:(master) python main.py /Users/qwr-and-dev2/Desktop/ipa/Runner\ 2019-12-03\ 15-10-33/Runner.ipa --taskId 0011 -o bctest/ 
[LOG] Extracting IPA File
[LOG] Unzipping
[LOG] Extract Done!
[LOG] check All kind of files Done!
[LOG] iOS Info.plist Analysis Started
[LOG] Checking Permissions
[LOG] Checking for Insecure Connections
编译bitcode  arm64
获取Xar
获取Xar错误
None
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    main(sys.argv)
  File "main.py", line 47, in main
    map(input_macho.buildBitcode, input_macho.getArchs())
  File "/Users/qwr-and-dev2/development/iPAObfuscator/macho.py", line 90, in buildBitcode
    bitcode_bundle = bundle.BitcodeBundle(arch,xarOut,output_path).run()
  File "/Users/qwr-and-dev2/development/iPAObfuscator/bundle.py", line 44, in __init__
    super(BitcodeBundle,self).__init__(bundle)
  File "/Users/qwr-and-dev2/development/iPAObfuscator/bundle.py", line 21, in __init__
    retInfo = Xar(ExtraxmlCmd).run()
  File "/Users/qwr-and-dev2/development/iPAObfuscator/cmd.py", line 66, in run
    self.runCmd()
  File "/Users/qwr-and-dev2/development/iPAObfuscator/cmd.py", line 26, in runCmd
    out = subprocess.check_output(self.cmd,stderr=subprocess.STDOUT,cwd=self.workDir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
➜  iPAObfuscator git:(master) ✗ python main.py /Users/qwr-and-dev2/Desktop/ipa/Runner\ 2019-12-03\ 15-10-33/Runner.ipa -mllvm -bcf -mllvm -bcf_loop=3 -mllvm -bcf_prob=40 -mllvm-fla -mllvm -split -mllvm -split_num=2
usage: main.py [-h] [-t TASK_ID] [-o OUTPUT] input_file
main.py: error: unrecognized arguments: -mllvm -bcf -mllvm -bcf_loop=3 -mllvm -bcf_prob=40 -mllvm-fla -mllvm -split -mllvm -split_num=2
➜  iPAObfuscator git:(master) ✗ python main.py bctest.ipa --taskId 0011 -o bctest/ -mllvm -bcf -mllvm -bcf_loop=3 -mllvm -bcf_prob=40 -mllvm-fla -mllvm -split -mllvm -split_num=2
usage: main.py [-h] [-t TASK_ID] [-o OUTPUT] input_file
main.py: error: unrecognized arguments: -mllvm -bcf -mllvm -bcf_loop=3 -mllvm -bcf_prob=40 -mllvm-fla -mllvm -split -mllvm -split_num=2
➜  iPAObfuscator git:(master) ✗ python main.py /Users/qwr-and-dev2/Desktop/ipa/Runner\ 2019-12-03\ 15-10-33/Runner.ipa --taskId 0011 -o bctest/
[LOG] Extracting IPA File
[LOG] check All kind of files Done!
[LOG] iOS Info.plist Analysis Started
[LOG] Checking Permissions
[LOG] Checking for Insecure Connections
编译bitcode  arm64
获取Xar
获取Xar错误
None
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    main(sys.argv)
  File "main.py", line 47, in main
    map(input_macho.buildBitcode, input_macho.getArchs())
  File "/Users/qwr-and-dev2/development/iPAObfuscator/macho.py", line 90, in buildBitcode
    bitcode_bundle = bundle.BitcodeBundle(arch,xarOut,output_path).run()
  File "/Users/qwr-and-dev2/development/iPAObfuscator/bundle.py", line 44, in __init__
    super(BitcodeBundle,self).__init__(bundle)
  File "/Users/qwr-and-dev2/development/iPAObfuscator/bundle.py", line 21, in __init__
    retInfo = Xar(ExtraxmlCmd).run()
  File "/Users/qwr-and-dev2/development/iPAObfuscator/cmd.py", line 66, in run
    self.runCmd()
  File "/Users/qwr-and-dev2/development/iPAObfuscator/cmd.py", line 26, in runCmd
    out = subprocess.check_output(self.cmd,stderr=subprocess.STDOUT,cwd=self.workDir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
➜  iPAObfuscator git:(master) ✗ clear 

➜  iPAObfuscator git:(master) ✗ python main.py /Users/qwr-and-dev2/Desktop/ipa/Runner\ 2019-12-03\ 15-10-33/Runner.ipa --taskId 0011 -o bctest/
[LOG] Extracting IPA File
[LOG] check All kind of files Done!
[LOG] iOS Info.plist Analysis Started
[LOG] Checking Permissions
[LOG] Checking for Insecure Connections
编译bitcode  arm64
获取Xar
获取Xar错误
None
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    main(sys.argv)
  File "main.py", line 47, in main
    map(input_macho.buildBitcode, input_macho.getArchs())
  File "/Users/qwr-and-dev2/development/iPAObfuscator/macho.py", line 90, in buildBitcode
    bitcode_bundle = bundle.BitcodeBundle(arch,xarOut,output_path).run()
  File "/Users/qwr-and-dev2/development/iPAObfuscator/bundle.py", line 44, in __init__
    super(BitcodeBundle,self).__init__(bundle)
  File "/Users/qwr-and-dev2/development/iPAObfuscator/bundle.py", line 21, in __init__
    retInfo = Xar(ExtraxmlCmd).run()
  File "/Users/qwr-and-dev2/development/iPAObfuscator/cmd.py", line 66, in run
    self.runCmd()
  File "/Users/qwr-and-dev2/development/iPAObfuscator/cmd.py", line 26, in runCmd
    out = subprocess.check_output(self.cmd,stderr=subprocess.STDOUT,cwd=self.workDir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
➜  iPAObfuscator git:(master) ✗ clear                                                                                                          

➜  iPAObfuscator git:(master) ✗ python main.py
usage: main.py [-h] [-t TASK_ID] [-o OUTPUT] input_file
main.py: error: too few arguments
➜  iPAObfuscator git:(master) ✗ python main.py Runner.ipa --taskId 0001 -o bctest/                                  
[LOG] Extracting IPA File
[LOG] Unzipping
[LOG] Extract Done!
[LOG] check All kind of files Done!
[LOG] iOS Info.plist Analysis Started
[LOG] Checking Permissions
[LOG] Checking for Insecure Connections
编译bitcode  arm64
获取Xar
获取Xar错误
None
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    main(sys.argv)
  File "main.py", line 47, in main
    map(input_macho.buildBitcode, input_macho.getArchs())
  File "/Users/qwr-and-dev2/development/iPAObfuscator/macho.py", line 90, in buildBitcode
    bitcode_bundle = bundle.BitcodeBundle(arch,xarOut,output_path).run()
  File "/Users/qwr-and-dev2/development/iPAObfuscator/bundle.py", line 44, in __init__
    super(BitcodeBundle,self).__init__(bundle)
  File "/Users/qwr-and-dev2/development/iPAObfuscator/bundle.py", line 21, in __init__
    retInfo = Xar(ExtraxmlCmd).run()
  File "/Users/qwr-and-dev2/development/iPAObfuscator/cmd.py", line 66, in run
    self.runCmd()
  File "/Users/qwr-and-dev2/development/iPAObfuscator/cmd.py", line 26, in runCmd
    out = subprocess.check_output(self.cmd,stderr=subprocess.STDOUT,cwd=self.workDir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
➜  iPAObfuscator git:(master) ✗ python main.py -mllvm -bcf -mllvm -bcf_loop=3 -mllvm -bcf_prob=40 -mllvm-fla -mllvm -split -mllvm -split_num=2 Runner.ipa --taskId 0001 -o bctest/ 
usage: main.py [-h] [-t TASK_ID] [-o OUTPUT] input_file
main.py: error: unrecognized arguments: -mllvm -bcf -mllvm -bcf_loop=3 -mllvm -bcf_prob=40 -mllvm-fla -mllvm -split -mllvm -split_num=2
➜  iPAObfuscator git:(master) ✗ python main.py Runner.ipa --taskId 0001 -o bctest/ 
[LOG] Extracting IPA File
[LOG] check All kind of files Done!
[LOG] iOS Info.plist Analysis Started
[LOG] Checking Permissions
[LOG] Checking for Insecure Connections
编译bitcode  arm64
获取Xar
获取Xar错误
None
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    main(sys.argv)
  File "main.py", line 47, in main
    map(input_macho.buildBitcode, input_macho.getArchs())
  File "/Users/qwr-and-dev2/development/iPAObfuscator/macho.py", line 90, in buildBitcode
    bitcode_bundle = bundle.BitcodeBundle(arch,xarOut,output_path).run()
  File "/Users/qwr-and-dev2/development/iPAObfuscator/bundle.py", line 44, in __init__
    super(BitcodeBundle,self).__init__(bundle)
  File "/Users/qwr-and-dev2/development/iPAObfuscator/bundle.py", line 21, in __init__
    retInfo = Xar(ExtraxmlCmd).run()
  File "/Users/qwr-and-dev2/development/iPAObfuscator/cmd.py", line 66, in run
    self.runCmd()
  File "/Users/qwr-and-dev2/development/iPAObfuscator/cmd.py", line 26, in runCmd
    out = subprocess.check_output(self.cmd,stderr=subprocess.STDOUT,cwd=self.workDir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
➜  iPAObfuscator git:(master) ✗ python version
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'version': [Errno 2] No such file or directory
➜  iPAObfuscator git:(master) ✗ python --version
Python 2.7.16
➜  iPAObfuscator git:(master) ✗

**Comment by fukun521** [comment]
[LOG] Extracting IPA File
[LOG] check All kind of files Done!
[LOG] iOS Info.plist Analysis Started
[LOG] Checking Permissions
[LOG] Checking for Insecure Connections
编译bitcode  arm64
获取Xar
获取Xar错误
None
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    main(sys.argv)
  File "main.py", line 47, in main
    map(input_macho.buildBitcode, input_macho.getArchs())
  File "/Users/qwr-and-dev2/development/iPAObfuscator/macho.py", line 90, in buildBitcode
    bitcode_bundle = bundle.BitcodeBundle(arch,xarOut,output_path).run()
  File "/Users/qwr-and-dev2/development/iPAObfuscator/bundle.py", line 44, in __init__
    super(BitcodeBundle,self).__init__(bundle)
  File "/Users/qwr-and-dev2/development/iPAObfuscator/bundle.py", line 21, in __init__
    retInfo = Xar(ExtraxmlCmd).run()
  File "/Users/qwr-and-dev2/development/iPAObfuscator/cmd.py", line 66, in run
    self.runCmd()
  File "/Users/qwr-and-dev2/development/iPAObfuscator/cmd.py", line 26, in runCmd
    out = subprocess.check_output(self.cmd,stderr=subprocess.STDOUT,cwd=self.workDir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings

这个问题怎么解决，Xar是哪来的啊

**Comment by wswm2009** [comment]
> [LOG] Extracting IPA File
> [LOG] check All kind of files Done!
> [LOG] iOS Info.plist Analysis Started
> [LOG] Checking Permissions
> [LOG] Checking for Insecure Connections
> 编译bitcode arm64
> 获取Xar
> 获取Xar错误
> None
> Traceback (most recent call last):
> File "main.py", line 60, in
> main(sys.argv)
> File "main.py", line 47, in main
> map(input_macho.buildBitcode, input_macho.getArchs())
> File "/Users/qwr-and-dev2/development/iPAObfuscator/macho.py", line 90, in buildBitcode
> bitcode_bundle = bundle.BitcodeBundle(arch,xarOut,output_path).run()
> File "/Users/qwr-and-dev2/development/iPAObfuscator/bundle.py", line 44, in **init**
> super(BitcodeBundle,self).**init**(bundle)
> File "/Users/qwr-and-dev2/development/iPAObfuscator/bundle.py", line 21, in **init**
> retInfo = Xar(ExtraxmlCmd).run()
> File "/Users/qwr-and-dev2/development/iPAObfuscator/cmd.py", line 66, in run
> self.runCmd()
> File "/Users/qwr-and-dev2/development/iPAObfuscator/cmd.py", line 26, in runCmd
> out = subprocess.check_output(self.cmd,stderr=subprocess.STDOUT,cwd=self.workDir)
> File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 216, in check_output
> process = Popen(stdout=PIPE, *popenargs, **kwargs)
> File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in **init**
> errread, errwrite)
> File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
> raise child_exception
> TypeError: execv() arg 2 must contain only strings
> 
> 这个问题怎么解决，Xar是哪来的啊

你这个 ipa不支持bitcode

**Comment by godshield** [comment]
> [LOG] Extracting IPA File
> [LOG] check All kind of files Done!
> [LOG] iOS Info.plist Analysis Started
> [LOG] Checking Permissions
> [LOG] Checking for Insecure Connections
> 编译bitcode arm64
> 获取Xar
> 获取Xar错误
> None
> Traceback (most recent call last):
> File "main.py", line 60, in
> main(sys.argv)
> File "main.py", line 47, in main
> map(input_macho.buildBitcode, input_macho.getArchs())
> File "/Users/qwr-and-dev2/development/iPAObfuscator/macho.py", line 90, in buildBitcode
> bitcode_bundle = bundle.BitcodeBundle(arch,xarOut,output_path).run()
> File "/Users/qwr-and-dev2/development/iPAObfuscator/bundle.py", line 44, in **init**
> super(BitcodeBundle,self).**init**(bundle)
> File "/Users/qwr-and-dev2/development/iPAObfuscator/bundle.py", line 21, in **init**
> retInfo = Xar(ExtraxmlCmd).run()
> File "/Users/qwr-and-dev2/development/iPAObfuscator/cmd.py", line 66, in run
> self.runCmd()
> File "/Users/qwr-and-dev2/development/iPAObfuscator/cmd.py", line 26, in runCmd
> out = subprocess.check_output(self.cmd,stderr=subprocess.STDOUT,cwd=self.workDir)
> File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 216, in check_output
> process = Popen(stdout=PIPE, *popenargs, **kwargs)
> File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in **init**
> errread, errwrite)
> File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
> raise child_exception
> TypeError: execv() arg 2 must contain only strings
> 
> 这个问题怎么解决，Xar是哪来的啊

你的ipa不支持bitcode
